"""Customer Intelligence Studio - application entry point.

Run with:  streamlit run app.py

This landing page explains the product, then immediately shows live headline figures so
the demo is visible without any navigation, sign-up, key or upload.
"""

from __future__ import annotations

import streamlit as st

from src.analytics.insights import generate_insights
from src.analytics.kpis import HEADLINE_KPIS, compare_periods, population_summary
from src.data.loader import build_upload_source, validate_upload
from src.ui import components as ui
from src.ui.filters import current_filters
from src.ui.state import active_source, clear_source, set_source, using_upload
from src.utils.config import APP_NAME, APP_SUBTITLE, APP_TAGLINE

ui.configure_page("Overview")


def render_data_source_controls() -> None:
    """Demo/upload switch. The demo is the default so recruiters see data instantly."""
    with st.sidebar:
        st.markdown("#### Dataset")
        choice = st.radio(
            "Data source",
            ["Use demo dataset", "Upload dataset"],
            index=1 if using_upload() else 0,
            label_visibility="collapsed",
            key="cis_source_choice",
        )

        if choice == "Use demo dataset":
            if using_upload():
                clear_source()
                st.rerun()
            ui.dataset_badge(active_source().manifest, "demo")
            st.caption("Synthetic data generated locally from a fixed random seed.")
            return

        st.caption(
            "Your file is parsed in memory for this session only. It is not written to "
            "disk and is never sent to any external service."
        )
        uploaded = st.file_uploader("Journey CSV", type=["csv"], key="cis_upload")
        if uploaded is not None and st.button("Load file", use_container_width=True):
            result = validate_upload(uploaded)
            if not result.ok:
                for error in result.errors:
                    st.error(error)
            else:
                for warning in result.warnings:
                    st.warning(warning)
                set_source(build_upload_source(result.frame, uploaded.name))
                st.success(f"Loaded {len(result.frame):,} rows from {uploaded.name}.")
                st.rerun()

        if using_upload():
            ui.dataset_badge(active_source().manifest, "upload")


render_data_source_controls()

source = active_source()
filters = current_filters(source)

st.markdown(
    f'<div class="cis-title">{APP_NAME}</div><p class="cis-subtitle">{APP_SUBTITLE}</p>',
    unsafe_allow_html=True,
)
st.markdown(
    f'<p style="font-size:0.95rem;max-width:62ch;line-height:1.6;color:#33424f;">{APP_TAGLINE}</p>',
    unsafe_allow_html=True,
)
st.markdown('<hr class="cis-rule"/>', unsafe_allow_html=True)

summary = population_summary(source, filters)
kpis = compare_periods(source, filters, HEADLINE_KPIS)

ui.section(
    "At a glance",
    f"Last {filters.period_days} days, compared with the preceding {filters.period_days} days.",
)
ui.kpi_row(list(kpis.values()), columns=3)

st.write("")
left, right = st.columns([1.35, 1], gap="large")

with left:
    ui.section("What this application does")
    st.markdown(
        """
Customer Intelligence Studio turns raw journey-level records into decisions. It loads a
synthetic customer and mobility dataset into a **DuckDB** analytical database, computes
every metric in **SQL**, and presents the results as an interactive **Streamlit**
application.

**Use the pages in the sidebar to:**

- **Executive Overview** - headline KPIs, trends and automatically generated findings
- **Customer Explorer** - segment behaviour, engagement and side-by-side comparison
- **Service Performance** - on-time performance, delay distribution and peak analysis
- **Segmentation** - behavioural rules and K-means clustering of customer behaviour
- **Anomaly Detection** - days that fall outside their expected statistical range
- **Data Quality** - completeness, validity and how quality affects the numbers
- **Ask the Data** - natural-language questions answered from computed evidence
- **About** - architecture, methods, testing and deployment

Filters in the sidebar apply across every page.
        """
    )

with right:
    ui.section("What changed recently")
    insights = generate_insights(source, filters, limit=4, include_quality=False)
    ui.insight_list(insights, "No material changes in the selected period.")
    st.caption("Findings are generated by deterministic analytics, not by a language model.")

st.write("")
ui.population_banner(summary)

ui.footer(
    "Data is generated programmatically with a fixed seed; no real customer, health or "
    "operator data is used anywhere in this application."
)
